name: flutter_web_frame
description: Make Limit content size in Flutter Web/Desktop/PWA, Make your app that doesn't support responsiveness more focused on content
repository: https://github.com/wisnuwiry/flutter_web_frame
issue_tracker: https://github.com/wisnuwiry/flutter_web_frame/issues
homepage: https://github.com/wisnuwiry/flutter_web_frame
version: 1.0.0

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1

flutter: null
