name: flutter_web_frame
description: Limit size content Flutter Web/Desktop
repository: https://github.com/wisnuwiry/flutter_web_frame
issue_tracker: https://github.com/wisnuwiry/flutter_web_frame/issues
homepage: https://github.com/wisnuwiry/flutter_web_frame

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0

flutter: null
